# Config for FederationRecipe in federation.py
#
# To launch, run the following command from root torchtune directory:
#    tune run quantize --config quantization

output_dir: /tmp/torchtune/qwen2_5_0_5B/federated # /tmp may be deleted by your system. Change it to your preference.

#
# Model arguments
model:
  _component_: torchtune.models.qwen2_5.qwen2_5_0_5b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Qwen2.5-0.5B-Instruct
  checkpoint_files: [model.safetensors]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: QWEN2
resume_from_checkpoint: False

device: cuda
dtype: bf16
seed: 1234

federation:
  _component_: torchtune.training.federation.FullModelHFFederator
  participants:
    - uioGMzl7zqtkydxP66mJh9dZCaNnSWOb
    - etbefHUtU0XViIPrqo8nN2TlpvIUTdi7
